# Generated by Django 6.0.5 on 2026-05-23 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('course', 'Course'), ('book', 'Book'), ('website', 'Website'), ('video', 'Video'), ('podcast', 'Podcast'), ('docs', 'Documentation'), ('article', 'Article'), ('other', 'Other')], max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('source_author', models.CharField(blank=True, max_length=100, null=True)),
                ('source_creation_date', models.DateTimeField(auto_now_add=True)),
                ('source_last_modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source_name'), name='unique_source_per_user'), models.CheckConstraint(condition=models.Q(('source_type__in', ['book', 'article', 'website', 'video', 'podcast', 'course', 'docs', 'other'])), name='valid_source_type')],
            },
        ),
    ]
