# Generated by Django 6.0.5 on 2026-06-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('unit_last_modified_date', models.DateTimeField(auto_now=True)),
                ('unit_order', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='notes.source')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'unit_name'), name='unique_unit_per_source')],
            },
        ),
    ]
